ballots/urls.py
from django.urls import path
from .views import AddBallotView, ArchivedBallotsView, BallotEditView, BallotAdminView, PublishedBallotsView, \
    AddQuestionView, AddChoiceView, BallotDeleteView
from .views import BallotDetailView, PastBallotsView
from . import views

app_name = 'ballots'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:ballot_id>/', views.detail, name='detail'),
    path('<int:ballot_id>/vote/', views.vote, name='vote'),
    path('<int:ballot_id>/results/', views.results, name='results'),
    path('ballot-admin', BallotAdminView.as_view(), name='ballot-admin'),
    path('ballot-admin/published', PublishedBallotsView.as_view(), name='published'),
    path('ballot-admin/past', PastBallotsView.as_view(), name='past'),
    path('ballot-admin/archived', ArchivedBallotsView.as_view(), name='archived'),
    path('add/', AddBallotView.as_view(), name='add'),
    path('<int:pk>/edit', BallotEditView.as_view(), name='edit'),
    path('<int:pk>/detail', BallotDetailView.as_view(), name='ballot-detail'),
    path('<int:pk>/questions/', AddQuestionView.as_view(), name='questions'),
    path('<int:pk>/choices/', AddChoiceView.as_view(), name='choices'),
    path('<int:pk>/delete', BallotDeleteView.as_view(), name='delete'),
]

blind_voting_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ballots.urls")),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html'), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete')
]

ballots/models.py
import datetime
import uuid

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


# Create your models here.
from django_cryptography.fields import encrypt


def now_plus_7():
    return timezone.now() + datetime.timedelta(days=7)

def now_plus_30():
    return timezone.now() + datetime.timedelta(days=30)


class Ballot(models.Model):
    ballot_title = models.TextField(max_length=200, default="")
    ballot_description = models.TextField(max_length=200, default="", blank=True)
    pub_date = models.DateTimeField('date published', default=now_plus_7)
    due_date = models.DateTimeField('due date', default=now_plus_30)
    district = models.CharField(max_length=50, blank=True)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # Checks if the due date is after publish date
    def clean(self):
        if self.due_date < self.pub_date:
            raise ValidationError(_('Due Date should be further in the future than Publish Date.'), code='invalid')

    def __str__(self):
        return self.ballot_title

    def get_absolute_url(self):
        return reverse('ballots:edit', kwargs={'slug': self.slug})


class Question(models.Model):
    ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
    question_text = models.TextField(max_length=200)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0, editable=False)

    def __str__(self):
        return self.choice_text

class CastBallot(models.Model):
    assoc_ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)

class CastVote(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    ballot = models.ForeignKey(CastBallot, on_delete=models.CASCADE)

class VoteRecord(models.Model):
    assoc_ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
    voter_signature = models.CharField(max_length=50)

ballots/forms.py
from django.utils import timezone
import datetime
from django import forms
from django.core.exceptions import ValidationError

from .models import Ballot, Question, Choice
from django.forms.models import inlineformset_factory

def now_plus_7():
    return timezone.now() + datetime.timedelta(days=7)

class AddBallotForm(forms.ModelForm):
    class Meta:
        model = Ballot
        fields = {'ballot_title', 'ballot_description', 'pub_date', 'due_date', 'district'}
        widgets = {
            'ballot_title': forms.TextInput(attrs={'class': 'form-control'}),
            'ballot_description': forms.TextInput(attrs={'class': 'form-control'}),
            'district': forms.TextInput(attrs={'class': 'form-control'}),
        }

    field_order = ['ballot_title', 'ballot_description', 'pub_date', 'due_date', 'district']

    def clean_pub_date(self):
        data = self.cleaned_data.get('pub_date')
        if data <= timezone.now():
            raise forms.ValidationError("Invalid publication date - publication must be in the future")
        return data

    def clean(self):
        cleaned_data = super().clean()
        pub = cleaned_data.get('pub_date')
        due = cleaned_data.get('due_date')

        if pub and due:
            if pub >= due:
                raise ValidationError("Invalid publication date - publication must be before due date")


BallotQuestionFormset = inlineformset_factory(Ballot, Question, fields=('question_text',))


QuestionChoiceFormset = inlineformset_factory(Question, Choice, fields=('choice_text',))

ballots/views.py
import datetime

from django.contrib.auth.views import redirect_to_login
from django.core.signing import Signer
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_list_or_404, render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.utils import timezone
from django.views.generic import UpdateView, CreateView, ListView, FormView, DeleteView
from django.views.generic.detail import SingleObjectMixin, DetailView
from .forms import AddBallotForm, BallotQuestionFormset, QuestionChoiceFormset

# Create your views here.

from ballots.models import Ballot, Question, Choice, CastVote, VoteRecord, CastBallot


def index(request):
    if not request.user.is_authenticated:
        return redirect('/users/login/')
    signer = Signer()
    sign = signer.sign(request.user.profile.sign)
    sign = sign[51:]
    today = timezone.now()
    vote_records = VoteRecord.objects.filter(voter_signature__exact=sign)
    finished_ballot_ids = []
    for record in vote_records:
        finished_ballot_ids.append(record.assoc_ballot.id)
    ballot_list = Ballot.objects.filter(pub_date__lte=today).filter(district__iexact=request.user.profile.district) \
        .exclude(id__in=finished_ballot_ids).order_by('due_date')
    finished_ballots = Ballot.objects.filter(pub_date__lte=today).filter(district__iexact=request.user.profile.district)\
        .filter(id__in=finished_ballot_ids).filter(due_date__gte=today).order_by('due_date')
    old_ballots = Ballot.objects.filter(due_date__lte=today).filter(district__iexact=request.user.profile.district)
    context = {"ballot_list": ballot_list, "finished_ballots": finished_ballots, "old_ballots": old_ballots, "today": today}
    return render(request, 'ballots/index.html', context=context)


def detail(request, ballot_id):
    if not request.user.is_authenticated:
        return redirect('/users/login/')
    try:
        ballot = Ballot.objects.get(pk=ballot_id)
        question_list = Question.objects.filter(ballot=ballot_id)
        b_id = ballot_id
        context = {'ballot': ballot, 'question_list': question_list, 'current_b_id': b_id}
    except Ballot.DoesNotExist:
        raise Http404("Ballot does not exist")
    signer = Signer()
    sign = signer.sign(request.user.profile.sign)
    sign = sign[51:]
    if ballot.due_date > timezone.now() and ballot.pub_date < timezone.now()\
            and ballot.district.lower() == request.user.profile.district.lower() and not\
            VoteRecord.objects.filter(voter_signature=sign).filter(assoc_ballot=ballot).exists():
        return render(request, 'ballots/detail.html', context=context)
    else:
        raise PermissionDenied


def detail_q(request, ballot_id, question_id):
    if not request.user.is_authenticated:
        return redirect('/users/login/')
    try:

        ballot = Ballot.objects.get(pk=ballot_id)
        current_ballot = ballot_id
        question = get_object_or_404(Question, pk=question_id)
        context = {'current_b_id': current_ballot, 'question': question}
    except Ballot.DoesNotExist:
        raise Http404("Ballot does not exist")
    if ballot.pub_date > timezone.now() or ballot.due_date < timezone.now() \
            or ballot.district.lower() != request.user.profile.district.lower():
        return redirect(reverse('ballots:index'))
    return render(request, 'ballots/detail.html', context=context)


def results(request, ballot_id):
    try:
        ballot = Ballot.objects.get(pk=ballot_id)
        question_list = Question.objects.filter(ballot=ballot_id)
        context = {'ballot': ballot, 'question_list': question_list}
    except Ballot.DoesNotExist:
        raise Http404("Ballot does not exist")
    if ballot.due_date > timezone.now():
        return redirect(reverse('ballots:index'))
    for question in question_list:
        choices = Choice.objects.filter(question=question)
        for choice in choices:
            choice.votes = CastVote.objects.filter(choice=choice).count()
            choice.save()
    return render(request, 'ballots/vote.html', context=context)



def vote(request, ballot_id):
    if not request.user.is_authenticated:
        return redirect('/users/login/')
    # print(request.POST['choice'])
    ballot = get_object_or_404(Ballot, pk=ballot_id)
    questions = get_list_or_404(Question, ballot=ballot)
    signer = Signer()
    sign = signer.sign(request.user.profile.sign)
    sign = sign[51:]
    if ballot.pub_date > timezone.now() or ballot.due_date < timezone.now() \
            or ballot.district.lower() != request.user.profile.district.lower()\
            or VoteRecord.objects.filter(voter_signature=sign).filter(assoc_ballot=ballot).exists():
        return redirect(reverse('ballots:index'))
    if questions:
        selected_choices = []
        for question in questions:
            if request.POST.get(question.question_text):
                selected_choices.append(question.choice_set.get(pk=request.POST[question.question_text]))
        if len(selected_choices) > 0:
            signer = Signer()
            sign = signer.sign(request.user.profile.sign)
            sign = sign[51:]
            new_record = VoteRecord.objects.create(assoc_ballot=ballot, voter_signature=sign)
            new_record.save()
            new_ballot = CastBallot.objects.create(assoc_ballot=ballot)
            new_ballot.save()
            for choice in selected_choices:
                new_vote = CastVote.objects.create(choice=choice, ballot=new_ballot)
                new_vote.save()
    return HttpResponseRedirect(reverse('ballots:index'))


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('/users/login/')
        if not self.has_permission():
            return redirect(reverse('ballots:index'))
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class BallotAdminView(UserAccessMixin, ListView):
    raise_exception = False
    permission_required = 'ballot.change_ballot'

    model = Ballot
    template_name = "ballot_admin.html"
    context_object_name = "ballots"

    def get_queryset(self, *args, **kwargs):
        return Ballot.objects.filter(pub_date__gte=timezone.now())


class PublishedBallotsView(UserAccessMixin, ListView):
    permission_required = 'ballot.change_ballot'

    model = Ballot
    template_name = "published-ballots.html"
    context_object_name = "ballots"

    def get_queryset(self, *args, **kwargs):
        return Ballot.objects.filter(pub_date__lte=timezone.now()).filter(due_date__gte=timezone.now())


class PastBallotsView(UserAccessMixin, ListView):
    permission_required = 'ballot.change_ballot'

    model = Ballot
    template_name = "past-ballots.html"
    context_object_name = "ballots"

    def get_queryset(self, *args, **kwargs):
        return Ballot.objects.filter(due_date__lte=timezone.now()).filter(due_date__gte=timezone.now() - datetime.timedelta(days=365.25))


class ArchivedBallotsView(UserAccessMixin, ListView):
    permission_required = "ballot.change_ballot"

    model = Ballot
    template_name = "archived-ballots.html"
    context_object_name = "ballots"

    def get_queryset(self, *args, **kwargs):
        return Ballot.objects.filter(due_date__lte=timezone.now() - datetime.timedelta(days=365.24))

class AddBallotView(UserAccessMixin, CreateView):
    permission_required = 'ballot.change_ballot'

    template_name = 'add.html'
    form_class = AddBallotForm
    success_url = '/ballot-admin'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class BallotEditView(UserAccessMixin, UpdateView):
    permission_required = 'ballot.change_ballot'

    model = Ballot
    form_class = AddBallotForm
    template_name = 'ballotedit.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        if(self.get_object().pub_date <= timezone.now()):
            return redirect('/ballot-admin')
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('ballots:ballot-detail', kwargs={'pk': self.object.pk})


class AddQuestionView(UserAccessMixin, SingleObjectMixin, FormView):
    permission_required = 'ballot.change_ballot'

    model = Question
    template_name = 'addquestion.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Ballot.objects.all())
        if (self.object.pub_date <= timezone.now()):
            return redirect('/ballot-admin')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Ballot.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return BallotQuestionFormset(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Changes were saved.'
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('ballots:questions', kwargs={'pk': self.object.pk})


class AddChoiceView(UserAccessMixin, SingleObjectMixin, FormView):
    permission_required = 'ballot.change_ballot'

    model = Choice
    template_name = 'addchoice.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Question.objects.all())
        if (self.object.ballot.pub_date <= timezone.now()):
            return redirect('/ballot-admin')

ballots/templates/add.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Ballots</h1>
        <p class="lead">Ballots managed under your district</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
    <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Return</a>
</div>
{% endblock %}

ballots/templates/addchoice.html
{% extends 'base.html' %}

{% block title %}Editing Choices {{ question.question_text }}{% endblock %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.management_form }}
    {{ form.non_form_errors }}

    <h3>Update Choices</h3>
    {% for choice_form in form.forms %}
      <hr>
      <h5>
        {% if choice_form.instance.id %}
          Choice: {{ choice_form.instance.choice_text }}
        {% else %}
          {% if form.forms|length > 1 %}
            Add another Choice
          {% else %}
            Add a Choice
          {% endif %}
        {% endif %}
      </h5>
      {% for hidden_field in question_form.hidden_fields %}
        {{ hidden_field.errors }}
      {% endfor %}
      <table>
        {{ choice_form.as_table }}
      </table>
    {% endfor %}
    <hr>
    <p>
      <button type="submit" value="Update Choices" class="btn btn-primary w-100 mb-3">Update Choices</button>
      <a href="{% url 'ballots:ballot-detail' pk=question.ballot.pk%}" role="button" class="btn btn-secondary w-100">Cancel</a>
    </p>
  </form>

{% endblock content %}

ballots/templates/archived-ballots.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a href="/add/">add poll</a>
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Ballots</h1>
        <p class="lead">Ballots whose due date were over one year ago</p>
    </div>
    <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Unpublished Ballots </a>|
    <a class="text-dark" href="{% url 'ballots:published'%}">Published Ballots </a>|
    <a class="text-dark" href="{% url 'ballots:past'%}">Past Due Ballots</a>
    <div class="py-5">
        <div class="row">
            {% for ballot in ballots %}
            <div class="col-md-4">
                <a class="text-dark" href="{% url 'ballots:ballot-detail' pk=ballot.pk %}">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                {{book.title|truncatechars:50}}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ballot.district}}</small>
                                <small class="text-muted">{{ballot.ballot_title}}</small>
                            </div>
                            <small class="text-muted">{{time}}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ballots/templates/ballot-delete.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
    <form method='POST'>{% csrf_token %}
    <h1>Are you sure you want to delete ballot: "{{object.ballot_title }}"?</h1>
    <p><input type='submit' class="btn btn-primary" value='Yes' /></p>
        <a href="{% url 'ballots:ballot-detail' pk=ballot.pk%}" class="btn btn-secondary">Cancel</a>
</form>
<p>{{ object.content }}</p>
{% endblock %}

ballots/templates/ballot-detail.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ballot.ballot_title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ballot.ballot_description}}</small>
                <small class="text-muted">{{ballot.pub_date}}</small>
                <small class="text-muted">{{ballot.due_date}}</small>
                <small class="text-muted">{{ballot.district}}</small>
            </div>
        </div>
        {% for question in ballot.question_set.all %}
            <p style="font-size:160%;"> {{forloop.counter}}. {{question.question_text}}</p>
            {% for choice in question.choice_set.all %}
            <p> &emsp; {{choice.choice_text}} </p>
            {% endfor %}
            <a class="btn btn-secondary btn-sm" href="{% url 'ballots:choices' pk=question.pk %}">Add Choices</a>
            <p>
            <!--Spacing Between Questions-->
            </p>
        {% endfor %}
        {% if ballot.pub_date >= today %}
        <div>
            <a class="btn btn-primary btn-sm" href="{% url 'ballots:questions' pk=ballot.pk %}">Add Questions</a>
            <p>
            <!--Spacing Between Questions-->
            </p>
        </div>
        <a href="{% url 'ballots:edit' pk=ballot.pk %}" class="btn btn-primary btn-sm" >Edit</a>
        <a href="{% url 'ballots:delete' pk=ballot.pk %}" class="btn btn-primary btn-sm" >Delete</a>
        {% endif %}
        <div>
            <p>
            <!--Spacing Between Questions-->
            </p>
        </div>
         <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Return</a>
    </div>
    {% endblock %}

ballots/templates/ballot_admin.html
{% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Ballots</h1>
            <p class="lead">Ballots managed under your district</p>
        </div>
        <a class="text-dark" href="{% url 'ballots:published'%}">Published Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:past'%}">Past Due Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:archived'%}">Archived Ballots</a>
        <div class="py-5">
            <div class="row">
                {% for ballot in ballots %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'ballots:ballot-detail' pk=ballot.pk %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{ballot.district}}</small>
                                    <small class="text-muted">{{ballot.ballot_title}}</small>
                                </div>
                                <small class="text-muted">{{time}}</small>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <a href="/add/" class="btn btn-secondary btn-sm" >add poll</a>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

ballots/templates/ballotedit.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Ballots</h1>
        <p class="lead">Ballots managed under your district</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
                <form method = post>
                </form>
            </div>
        </div>
    </div>
    <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Return</a>
</div>
{% endblock %}

ballots/templates/past-ballots.html
{% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Ballots</h1>
            <p class="lead">Ballots managed under your district</p>
        </div>
        <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Unpublished Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:published'%}">Published Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:archived'%}">Archived Ballots</a>
        <div class="py-5">
            <div class="row">
                {% for ballot in ballots %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'ballots:ballot-detail' pk=ballot.pk %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{ballot.district}}</small>
                                    <small class="text-muted">{{ballot.ballot_title}}</small>
                                </div>
                                <small class="text-muted">{{time}}</small>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

ballots/templates/published-ballots.html
{% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Ballots</h1>
            <p class="lead">Ballots managed under your district</p>
        </div>
        <a class="text-dark" href="{% url 'ballots:ballot-admin'%}">Unpublished Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:past'%}">Past Due Ballots </a>|
        <a class="text-dark" href="{% url 'ballots:archived'%}">Archived Ballots</a>
        <div class="py-5">
            <div class="row">
                {% for ballot in ballots %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'ballots:ballot-detail' pk=ballot.pk %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{ballot.district}}</small>
                                    <small class="text-muted">{{ballot.ballot_title}}</small>
                                </div>
                                <small class="text-muted">{{time}}</small>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}